### ISSUE TITLE
Arreglen su toyo....

### ISSUE THREAD

**Issue by elpargo** [developersdo/dgii-consultas#5]
Ustedes son unos tollozos....

@amhed borrando la vaina de el. Y mi fork bien gracias .... https://github.com/elpargo/dgii-consultas

Entonces viene @danielgpm a hacer un toyo....

Y al final arrrhhhh hagan lo que quieran ahi esta el codigo

**Comment by amhed** [comment]
#cambiatuatitú

Que es lo que pasa?

**Comment by elpargo** [comment]
I don't know how to. Merge that shit.... Y me han cambiando el. Master/repo
como tres veces

**Comment by danielgpm** [comment]
@elpargo care to explain porque lo que subí es un toyo?

**Comment by amhed** [comment]
http://gifrific.com/wp-content/uploads/2012/06/dis-gun-be-gud.gif

**Comment by elpargo** [comment]
Wtf dude... Don't close it. I can't friking request a pull request....
Help. Me fix it.

**Comment by amhed** [comment]
Para poder hacer un pull request tienes que hacer un fork de este repositorio, hacerle un clon a tu workstation, hacer los cambios y luego hacer un PR desde tu fork en Github

**Comment by amhed** [comment]
Ahora mismo no puedes hacer el pull request porque tu repo original apuntaba a la version que estaba en mi cuenta personal, pero eso se cambió el primer día cuando lo anuncié en devs.do

**Comment by danielgpm** [comment]
@elpargo y btw no veo como tu versión es mejor, primero hardcodeando todo en un mismo source (no unitest) y 2do creando un server ahí mismo cuando se supone que sólo es el cliente no el API

**Comment by amhed** [comment]
:monkey_face: pargo ven a pedir perdon aquí

**Comment by elpargo** [comment]
@danielgpm el toyo es del repo no del codigo tuyo.

Dicho eso se supone que es un server/api (mira el original de C#)

**Comment by danielgpm** [comment]
@elpargo, consulta-dgii-csharp (que fue la versión que vi) solo es cliente o no @amhed? Pero na, si quieres subir tu versión hazle fork al máster, utiliza el config.json, pon los unitests para el server y actualiza los requirements (No solo subas un gist como hiciste :p)

**Comment by carlosvasquez** [comment]
Creo que arrancaron a trabajar desde versiones diferentes. Solo bajen el master del developersdo, arreglen los conflictos, den un merge y git pull. Dejen un source que sea cliente y otro server/api si quieren y así resolverían pero no duplicidad del mismo proyecto con dos nombres.

**Comment by eneldoserrata** [comment]
https://arthurdejong.org/python-stdnum/doc/1.11/stdnum.do.cedula#module-stdnum.do.cedula
https://arthurdejong.org/python-stdnum/doc/1.11/stdnum.do.ncf#module-stdnum.do.ncf
https://arthurdejong.org/python-stdnum/doc/1.11/stdnum.do.rnc#module-stdnum.do.rnc
